#%RAML 1.0 Trait
 queryParameters:
           symbol:
             required: false
             type: string
             example: "APPL"
           exchangeRate :
             required: false
             type: string
             example: "NASDAQ"
           operation:
             required: false
             type: string
             example: "Sell"
           limit:
             required: false
             type: integer
             example: 10